create extension if not exists pgcrypto;

create type public.user_role as enum ('user','moderator','owner');
create type public.submission_status as enum ('pending','approved','rejected','placed');
create type public.level_status as enum ('active','legacy');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email_optional text,
  role public.user_role not null default 'user',
  points integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.levels (
  id bigint generated by default as identity primary key,
  gd_level_id text not null,
  name text not null,
  creator text,
  verifier text,
  description text,
  placement integer unique,
  points integer not null default 250,
  status public.level_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  level_id bigint references public.levels(id) on delete cascade,
  submitter_id uuid not null references public.profiles(id) on delete cascade,
  gd_level_id text not null,
  level_name text not null,
  creator text,
  verifier text,
  youtube_url text not null,
  status public.submission_status not null default 'pending',
  reviewer_id uuid references public.profiles(id),
  rejection_reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table public.records (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  submission_id bigint references public.submissions(id) on delete set null,
  proof_url text not null,
  created_at timestamptz not null default now(),
  unique(level_id, player_id)
);

create table public.placement_history (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  old_placement integer,
  new_placement integer,
  changed_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create index submissions_status_idx on public.submissions(status);
create index levels_placement_idx on public.levels(placement);
create index records_player_idx on public.records(player_id);

alter table public.profiles enable row level security;
alter table public.levels enable row level security;
alter table public.submissions enable row level security;
alter table public.records enable row level security;
alter table public.placement_history enable row level security;

create policy "public read profiles" on public.profiles for select using (true);
create policy "public read active levels" on public.levels for select using (status='active');
create policy "public read legacy levels" on public.levels for select using (status='legacy');
create policy "public read records" on public.records for select using (true);
create policy "public read placement history" on public.placement_history for select using (true);

create policy "users read own submissions" on public.submissions for select using (submitter_id = auth.uid());
create policy "users create submissions" on public.submissions for insert with check (submitter_id = auth.uid());
