alter type public.level_status add value if not exists 'list_percent';
alter table public.levels add column if not exists list_percent_value integer not null default 0 check (list_percent_value between 0 and 100);
alter table public.submissions add column if not exists record_type text not null default 'completion' check (record_type in ('completion','list_percent'));
alter table public.submissions add column if not exists progress_percent integer not null default 100 check (progress_percent between 1 and 100);
alter table public.records add column if not exists record_type text not null default 'completion' check (record_type in ('completion','list_percent'));
alter table public.records add column if not exists progress_percent integer not null default 100 check (progress_percent between 1 and 100);

create table if not exists public.announcements (id bigint generated by default as identity primary key, title text not null, body text not null, author_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.changelog (id bigint generated by default as identity primary key, title text not null, body text, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.reports (id bigint generated by default as identity primary key, reporter_id uuid not null references public.profiles(id) on delete cascade, level_id bigint references public.levels(id) on delete set null, reason text not null, status text not null default 'open' check (status in ('open','resolved')), created_at timestamptz not null default now());
alter table public.announcements enable row level security; alter table public.changelog enable row level security; alter table public.reports enable row level security;
create policy "public read announcements" on public.announcements for select using (true);
create policy "public read changelog" on public.changelog for select using (true);
create policy "users create reports" on public.reports for insert with check (reporter_id = auth.uid());
