-- GAFK LIST community expansion. Run once in Supabase SQL Editor.
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists banner_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists banned_at timestamptz;
alter table public.profiles add column if not exists ban_reason text;
alter table public.site_settings add column if not exists featured_level_id bigint references public.levels(id) on delete set null;

create table if not exists public.level_comments (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  detail text,
  created_at timestamptz not null default now()
);
create table if not exists public.list_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.list_snapshot_levels (
  snapshot_id bigint not null references public.list_snapshots(id) on delete cascade,
  level_id bigint references public.levels(id) on delete set null,
  name text not null,
  creator text,
  placement integer not null,
  points integer not null,
  aredl_placement integer,
  primary key(snapshot_id, placement)
);
create index if not exists level_comments_level_idx on public.level_comments(level_id, created_at desc);
create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);

alter table public.level_comments enable row level security;
alter table public.notifications enable row level security;
alter table public.activity_log enable row level security;
alter table public.list_snapshots enable row level security;
alter table public.list_snapshot_levels enable row level security;
create policy "public read site settings" on public.site_settings for select using (true);
create policy "public read visible comments" on public.level_comments for select using (hidden = false);
create policy "users create comments" on public.level_comments for insert with check (author_id = auth.uid());
create policy "users read own notifications" on public.notifications for select using (user_id = auth.uid());
create policy "users update own notifications" on public.notifications for update using (user_id = auth.uid());
create policy "public read activity" on public.activity_log for select using (true);
create policy "public read snapshots" on public.list_snapshots for select using (true);
create policy "public read snapshot levels" on public.list_snapshot_levels for select using (true);
