'use client';

import { useMemo, useState } from 'react';
import PlacementForm from '@/components/PlacementForm';

type Level = { id: number; name: string; creator: string | null; placement: number; points: number; aredl_placement: number | null; list_percent_value: number };

export default function PlacedLevelManager({ levels, canDelete }: { levels: Level[]; canDelete: boolean }) {
  const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [deleting, setDeleting] = useState<number | null>(null);
  const shown = useMemo(() => levels.filter((level) => `${level.name} ${level.creator ?? ''} ${level.placement} ${level.aredl_placement ?? ''}`.toLowerCase().includes(search.toLowerCase())).slice(0, 100), [levels, search]);
  async function remove(level: Level) { if (!window.confirm(`${level.name} levelini kalıcı olarak silmek istiyor musun?`)) return; setDeleting(level.id); const response = await fetch(`/api/levels/${level.id}`, { method: 'DELETE' }); const body = await response.json(); setDeleting(null); setMessage(response.ok ? 'Level deleted; placements and points updated.' : body.error || 'Level could not be deleted.'); if (response.ok) window.location.reload(); }
  async function saveAredl(level: Level, value: string) { const aredlPlacement = value ? Number(value) : null; const response = await fetch(`/api/levels/${level.id}/aredl`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ aredlPlacement }) }); const body = await response.json(); setMessage(response.ok ? 'AREDL placement saved.' : body.error || 'AREDL placement could not be saved.'); }
  async function saveListPercent(level: Level, value: string) { const response = await fetch(`/api/levels/${level.id}/list-percent`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ value: Number(value) }) }); const body = await response.json(); setMessage(response.ok ? 'List% value saved.' : body.error || 'List% could not be saved.'); }
  async function autoRank() { if (!window.confirm('AREDL placement values will replace the current GAFK order. Continue?')) return; const response = await fetch('/api/admin/aredl-rank', { method: 'POST' }); const body = await response.json(); setMessage(response.ok ? `Auto-ranked ${body.updated} levels from AREDL.` : body.error || 'Auto-rank failed.'); if (response.ok) window.location.reload(); }
  return <section className="admin-section"><h2>Manual & AREDL Placement</h2><p className="muted">Manual placement is always available. Enter an AREDL placement then use Auto Rank when you want GAFK to follow AREDL order.</p><button className="btn" onClick={autoRank}>Auto rank from AREDL</button><input className="input admin-search" placeholder="Search level, creator, GAFK or AREDL placement…" value={search} onChange={(event) => setSearch(event.target.value)} />
    <div className="admin-results">{shown.map((level) => <article className="card" key={level.id}><b>#{level.placement} — {level.name}</b><p className="muted">{level.creator || 'Unknown creator'} · {level.points} pts</p><label className="muted">AREDL placement</label><input className="input placement-input" type="number" min="1" defaultValue={level.aredl_placement ?? ''} onBlur={(event) => saveAredl(level, event.target.value)} /><label className="muted">Level List% value</label><input className="input placement-input" type="number" min="0" max="100" defaultValue={level.list_percent_value} onBlur={(event) => saveListPercent(level, event.target.value)} /><PlacementForm levelId={level.id} currentPlacement={level.placement} />{canDelete && <button className="btn secondary" disabled={deleting === level.id} onClick={() => remove(level)}>Delete level</button>}</article>)}{shown.length === 0 && <p className="muted">No matching placed levels.</p>}{message && <p className="muted">{message}</p>}</div>
  </section>;
}
